- "一班"
- "二班"
- "三班"
- "四班"
- "五班"
- "六班"
- "七班"
- "八班"
- "九班"
- "十班"
- "十一班"
- "十二班"
- "十三班"
- "十四班"
- "十五班"
- "十六班"
- "十七班"
- "十八班"
- "十九班"
- "二十班"
- "二一班"
- "二二班"
- "二三班"
- "二四班"
- "二五班"
- "二六班"
- "二七班"
- "二八班"